spring:
  openai:
    api:
      key: sk-0b373e0332c5407d9db5fcaf97a4a958
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat-model: qwen-turbo
      embedding-model: text-embedding-v3


  chroma:
    server:
      host: localhost
      port: 8585