server:
  port: 9999
spring:
  application:
    name: Mall-Server
  http:
    encoding:
      charset: utf-8
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    include: redis,mail,jdbc,langchain4j
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
      max-request-size: 7MB
      location: ${java.io.tmpdir}
  jpa:
    open-in-view: false
  mvc:
    cors:
      allowed-origins: "http://localhost:8080"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
    servlet:
      load-on-startup: 1

sa-token:
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  is-print: false

admin:
  email: admin@qq.com
  userName: 超级管理员
  password: admin@qq.com
